Repository Polymer/tools, pull requests merged in 2019-07, with the labels that each got.

#3439 fixed --allow-origin switch not being added to serverOptions
  packages/cli/src/commands/serve.ts
Labels: cla: yes

#3396 update bower version
  packages/cli/package.json
Labels: cla: yes

#676 analyzer: merge property info from constructors
  packages/analyzer/CHANGELOG.md
  packages/analyzer/src/javascript/class-scanner.ts
  packages/analyzer/src/test/javascript/class-scanner_test.ts
  packages/analyzer/src/test/static/class/class-properties.js
Labels: cla: yes

#3444 Updated chalk to latest version; implemented the updates from #623
  package-lock.json
  packages/analyzer/package-lock.json
  packages/browser-capabilities/package-lock.json
  packages/build/package-lock.json
  packages/bundler/package-lock.json
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/cli/src/commands/help.ts
  packages/cli/src/commands/lint.ts
  packages/cli/src/init/application/application.ts
  packages/cli/src/init/element/element.ts
  packages/cli/src/init/init.ts
  packages/cli/src/lint/lint.ts
  packages/common/package-lock.json
  packages/dom5/package-lock.json
  packages/editor-service/package-lock.json
  packages/esm-amd-loader/package-lock.json
  packages/gen-typescript-declarations/package-lock.json
  packages/linter/package-lock.json
  packages/modulizer/package-lock.json
  packages/polyserve/package-lock.json
  packages/project-config/package-lock.json
  packages/wct-browser-legacy/package-lock.json
  packages/wct-browser-legacy/test/package-lock.json
  packages/wct-local/package-lock.json
  packages/wct-mocha/package-lock.json
  packages/wct-mocha/test/package-lock.json
  packages/wct-sauce/package-lock.json
  packages/web-component-tester/package-lock.json
  packages/workspaces/package-lock.json
Labels: cla: yes

#429 Unskip editor service tests now that we are retrying.
  packages/editor-service/src/test/auto-completer_test.ts
  packages/editor-service/src/test/definition-finder_test.ts
Labels: cla: yes

#3309 Add support for selenium-java-args
  packages/wct-local/custom_typings/selenium-standalone.d.ts
  packages/wct-local/package.json
  packages/wct-local/src/plugin.ts
  packages/wct-local/src/selenium.ts
Labels: Area: Test, Package: wct-local, Type: Enhancement, cla: yes

#3443 Added --allow-origin to the polymer serve command
  packages/cli/CHANGELOG.md
  packages/cli/src/commands/serve.ts
Labels: cla: no

#3445 [wct-local] Added javaArgs to plugin options.
  packages/wct-local/CHANGELOG.md
  packages/wct-local/custom_typings/selenium-standalone.d.ts
  packages/wct-local/package.json
  packages/wct-local/src/plugin.ts
  packages/wct-local/src/selenium.ts
Labels: Area: Test, Type: Enhancement, cla: no

#3446 Prepare release
  package-lock.json
  packages/analyzer/CHANGELOG.md
  packages/analyzer/package-lock.json
  packages/analyzer/package.json
  packages/build/package-lock.json
  packages/bundler/package-lock.json
  packages/cli/CHANGELOG.md
  packages/cli/package-lock.json
  packages/cli/package.json
  packages/common/package-lock.json
  packages/dom5/package-lock.json
  packages/editor-service/package-lock.json
  packages/esm-amd-loader/package-lock.json
  packages/gen-typescript-declarations/package-lock.json
  packages/linter/package-lock.json
  packages/modulizer/package-lock.json
  packages/polyserve/package-lock.json
  packages/project-config/package-lock.json
  packages/wct-browser-legacy/package-lock.json
  packages/wct-local/CHANGELOG.md
  packages/wct-local/package-lock.json
  packages/wct-local/package.json
  packages/wct-mocha/package-lock.json
  packages/wct-sauce/package-lock.json
  packages/web-component-tester/package-lock.json
  packages/workspaces/package-lock.json
Labels: cla: yes

#3449 Modulizer: fix readme add-import-meta default value and reference doc URL
  packages/modulizer/README.md
Labels: cla: yes
